language: ruby

cache:
  bundler: true
  directories:
  - vendor/bundle

rvm:
  - 2.3.1
  - jruby-9.0.5.0


before_install:
  - gem update --system '2.6.1'
  - gem update bundler
  - gem --version

script: "bundle exec rake test"

