language: ruby

cache:
  bundler: true
  directories:
  - vendor/bundle

rvm:
  - 2.3.2
  - 2.2.6
  - 2.1.9
  - ruby-2.0.0-p648


before_install:
  - gem update --system
  - gem update bundler
  - gem --version

script: "bundle exec rake test"

